<p>Hey @firstname@,</p>

<p>We see that you have initiated a password change request. Please use the link below to reset your password. Please note, this link will expire in 3 hours.</p><br>

<p><a href="@reseturl@">Click here to reset your password</a></p><br>

<p><i>Source Information: This automated message was generated by the <a href="@domain@">Psomas Intranet</a> @sourcemodule@ module. If you did not request a password reset, please forward this to email to webmaster@psomas.com.</i></p><br><br>