Hey @firstname@,

We see that you have initiated a password change request. Please use the link below to reset your password. Please note, this link will expire in 3 hours.

Password Reset Link: @reseturl@

Source Information: This automated message was generated by the Psomas Intranet login. If you did not request a password reset, please forward this to email to webmaster@psomas.com.